-- Add TIN fields to users table
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS tin_number VARCHAR(20) UNIQUE,
  ADD COLUMN IF NOT EXISTS tin_verified BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS taxpayer_type VARCHAR(100),
  ADD COLUMN IF NOT EXISTS region VARCHAR(100);
